export const ROUTES = {
    welcomeScreen: 'welcomeScreen',
    updateProfileSignUp: 'updateProfileSignUp',
    AppNavigator: 'AppNavigator',
    AlarmScreen:'AlarmScreen',
    preViewCall:'preViewCall',
    VideoCallScreen:'VideoCallScreen',
    Meeting: "Meeting_Screen",
    Login: 'Login',
    SignUp: 'SignUp',
    ConfirmPassword: 'ConfirmPassword',
    ForgotOTP: 'ForgotOTP',
    ForgotPassword: 'ForgotPassword',
    CalendarScreen: 'CalendarScreen',

    // App Navigator
    AppointmentsStack: 'AppointmentsStack',
    MyClientsStack: 'MyClientsStack',
    MyProfileStack: 'MyProfileStack',
    SettingsStack: 'SettingsStack',

    // Home Stack
    AppointmentListScreen: 'AppointmentListScreen',
    MyClientsScreen: 'MyClientsScreen',
    MyProfileScreen: 'MyProfileScreen',
    SettingScreen: 'SettingScreen',
    PromotionAndDiscount: 'PromotionAndDiscount',
    HelpScreen: 'HelpScreen',
    DeleteAccountScreen: 'DeleteAccountScreen',
    ClientsProfileScreen: 'ClientsProfileScreen',
    ClientSectionScreen: 'ClientSectionScreen',
    PersonalProfileScreen: 'PersonalProfileScreen', 
    CareProviderBioScreen: 'CareProviderBioScreen',
    MedicalLicenseScreen: 'MedicalLicenseScreen',
    AccountInformationScreen: 'AccountInformationScreen',
    PaymentProfileScreen:'PaymentProfileScreen',
    PaymentDetailsScreen:'PaymentDetailsScreen',
    SignTheContractScreen:'SignTheContractScreen',
    SignatureViewerScreen:'SignatureViewerScreen',
    VisitDetailScreen:'VisitDetailScreen',
    AddSessionRecord: 'AddSessionRecord',
    ConversationListScreen: 'ConversationListScreen',
    ChatScreenMainView: 'ChatScreenMainView',
    NotificationListScreen: 'NotificationListScreen',
    ServiceProfileScreen: 'ServiceProfileScreen',
    ReminderListScreen: 'ReminderListScreen',
    BookingHistory: 'BookingHistory',
    BusinessHours: 'BusinessHours',
    DurationAndPrice: 'DurationAndPrice',
    PrescriptionListScreen: 'PrescriptionListScreen',
    BookNewService: 'BookNewService',
    SuccessScreen: 'SuccessScreen',
    PrivacyPolicy: 'PrivacyPolicy',
    AfterContractSign: 'AfterContractSign',
    PrescriptionView: 'PrescriptionView',
    EnglishBioScreen: 'EnglishBioScreen',
    ArabicBioScreen: 'ArabicBioScreen',
    WorkAreas: 'WorkAreas',
    DeleteConfirmationScreen: 'DeleteConfirmationScreen',
  };
  